### ISSUE TITLE
Benchmark problem

### ISSUE THREAD

**Issue by Paultuc** [CryptoMiningInsider/TRex-Miner-Plugin-Adapter#1]
i have 4 gpu's in my rig
when i benchmark gpu no 1 gpu #0
it puts the benchmarks in gpu 2   gpu#1
also when i mine it switches the 1st and 2nd  gpu benchmarks and settings around

**Comment by CryptoMiningInsider** [comment]
On a test rig I have seen Nicehash switching the Device IDs on one of my rigs which is essentially the same issue you are seeing. For me its doing it on a Rig of full hash 3070s and a single 3060 V1 that's on the x16 slot on the motherboard.
The card on the motherboard is getting switched. I'm using driver 470.05

Examining the Trex Miner Plugin Adapter generated log and sample batch file shows the values sent in by Nicehash are incorrect.
I am researching this issue.

**Comment by Paultuc** [comment]
i have found a better method for using t-rex in nicehash

https://github.com/angelbbs/NiceHashMinerLegacy/releases/tag/Fork_Fix_43.2

**Comment by CryptoMiningInsider** [comment]
I would not trust the Fork Fix since it's from an unknown or (not well known) source.

**Comment by Jam-6** [comment]
> On a test rig I have seen Nicehash switching the Device IDs on one of my rigs which is essentially the same issue you are seeing. For me its doing it on a Rig of full hash 3070s and a single 3060 V1 that's on the x16 slot on the motherboard. The card on the motherboard is getting switched. I'm using driver 470.05
> 
> Examining the Trex Miner Plugin Adapter generated log and sample batch file shows the values sent in by Nicehash are incorrect. I am researching this issue.

Hey I'm also having this issue. Nicehash Launch parameters from one card end up being used for at least 2 cards in nbminer or trex. I've tried everything, reinstalled windows, moved pcie risers around, reinstalled drivers, msi afterburner, nicehash. 
I know it's not really much to do with you but do you have any more info or potential solutions?
I'm not having any luck googling this issue, this is the only place I've found anyone talking about it.
I am utilising a pci 1-4 splitter, not sure if that has anything to do with it.

Thanks

**Comment by Paultuc** [comment]
i have found a better method for using t-rex in nicehash

https://github.com/angelbbs/NiceHashMinerLegacy/releases/tag/Fork_Fix_43.2
