### ISSUE TITLE
JSON Support

### ISSUE THREAD

**Issue by bhedges81** [CryptoMiningInsider/TRex-Miner-Plugin-Adapter#2]
I tried to set --lhr-tune 74 --lhr-autotune-mode off in Extra Launch Parameters. After a bit I noticed LHR had dropped to 73. When reviewing the JSON I noticed autotune-mode was not in the file. Can it be added by adding the following to MinerOptionsPackage.json or does the Adapter also need an update to include it?

"type": "OptionWithSingleParameter",
      "id": "trex_lhr_autotune_mode",
      "short_name": null,
      "long_name": "--lhr-autotune-mode",
      "default_value": "full",
      "delimiter": null

**Comment by CryptoMiningInsider** [comment]
You should be able to add it without issue.

I will add more parameters (including this in next release)

Thanks

**Comment by bhedges81** [comment]
It passed correctly. 

[12380]   ******************* Launching TRex Miner Plugin Adapter BETA VERSION 0.1.20  By Crypto Mining Insider™ *******************

[12380]   Start Time: 16-Feb-2022 04:30:23 PM

[12380]   ===> Original Command Line:
"C:\Users\bhedges\AppData\Local\Programs\NiceHash Miner\miner_plugins\03f80500-94ec-11ea-a64d-17be303ea466\bins\16.0\t-rex.exe" --algo ethash --url stratum2+tcp://daggerhashimoto.usa-east.nicehash.com:3353 --user 3Aekdva94FWZtKHSqFn87YLnyUSe1W5R8N$0-2QgLJqypOl+5i31obnro-w --api-bind-http 127.0.0.1:4000 --api-bind-telnet 0 --devices 0 --lhr-tune 74 --lhr-autotune-mode off --no-watchdog

[12380]   ===> Updated Command Line:
"C:\Users\bhedges\AppData\Local\Programs\NiceHash Miner\miner_plugins\03f80500-94ec-11ea-a64d-17be303ea466\bins\16.0\t-rex-miner.exe" --algo ethash --url stratum2+tcp://daggerhashimoto.usa-east.nicehash.com:3353 --user 3Aekdva94FWZtKHSqFn87YLnyUSe1W5R8N$0-2QgLJqypOl+5i31obnro-w --api-bind-http 127.0.0.1:4000  --devices 0 --lhr-tune 74 --lhr-autotune-mode off --no-watchdog

[12380]   Created Sample Mining Batch File for mining ethash: trex-nicehash-start-ethash-sample.bat

[12380]   Starting Miner (t-rex-miner.exe) [20440] @ 16-Feb-2022 04:30:24 PM, Mining Algo: ethash

[12380]   Miner Process Started & Waiting... Mining Algo: ethash

**Comment by CryptoMiningInsider** [comment]
Great - Thanks for testing it !
