### ISSUE TITLE
LHR issue - Not sure if plugin adapter or T-rex miner

### ISSUE THREAD

**Issue by eblieb** [CryptoMiningInsider/TRex-Miner-Plugin-Adapter#6]
If I set my -lhr to above 74 no matter what I set it always starts at 74... I tried 74.6 and 75 but when i restart the miner it is still starting at 74. Not sure if this is a bug with the plugin adapter or t-rex miner.

**Comment by CryptoMiningInsider** [comment]
Trex parameter is --lhr-tune  
NBMiner is --lhr

**Comment by CryptoMiningInsider** [comment]
use the --lhr-tune parameter
